#!/usr/bin/env ansible-playbook
---
- name: Add necessary ssh public /etc/ansible/keys to default and required users.
  hosts: model-b
  any_errors_fatal: true
  tasks:

  - name: Adding public /etc/ansible/keys to Hyperiot Pirate Default User!
    authorized_key:
      user: pirate
      state: present
      key: '{{ item }}'
    with_file:
      - '/etc/ansible/keys/id_rsa.pub'
      - '/root/.ssh/id_ed25519.pub'
#      - '/var/lib/jenkins/.ssh/id_rsa.pub'

  #!!!! Root User
  - name: Adding public /etc/ansible/keys to Root User!
    authorized_key:
      user: root
      state: present
      key: '{{ item }}'
    with_file:
      - '/etc/ansible/keys/id_rsa.pub'
      - '/root/.ssh/id_ed25519.pub'
#      - '/var/lib/jenkins/.ssh/id_rsa.pub'
