#!/usr/bin/env ansible-playbook
---
- name: Force Public Keys onto host
  gather_facts: False
  hosts: hypriot-pirate
  tasks:
  - script: ../files/authorized_keys.sh  creates=/home/pirate/consoled.txt
