#!/usr/bin/env ansible-playbook
---
- name: bootstrap docker on debian/ubuntu
  gather_facts: False
  hosts: hypriot-pirate
  tasks:
  - script: ../files/authorized_keys.sh  creates=/home/pirate/consoled.txt
