#!/usr/bin/env ansible-playbook
---
- hosts: bp1
  tasks:
  - name: Ensure nfs directories and files
    file:
      path: "{{item}}"
      state: directory
      mode: 0775
      owner: root
      group: root
    with_items:
      - /nfs
      - /nfs/bin
      - /nfs/pihole
      - /nfs/pihole/etc
      - /nfs/pihole/dnsmasq.d
      - /nfs/network_devices
      - /nfs/ircd-hybrid
      - /nfs/hubot
      - /nfs/redis
      - /nfs/src
      - /nfs/src/{{ ansible_hostname }}
      - /nfs/log
      - /nfs/log/{{ ansible_default_ipv4.address }}
  - name: Ensure Pie Hole Service Script
    template:
      src: ../templates/pihole_docker_service.sh.j2
      dest: "/nfs/pihole/service.sh"
      mode: 0775
      owner: root
      group: root
  roles:
    - geerlingguy.nfs

- hosts: nfs-clients
  roles:
  - role: openmicroscopy.nfs-mount
    nfs_share_mounts:
      - path: /nfs
        location: bp1.pouliot.net:/nfs
        passno: 0
  tasks:
  - name: Ensure directories
    file:
      path: "{{item}}"
      state: directory
      mode: 0775
      owner: root
      group: root
    with_items:
      - /nfs/src/{{ ansible_hostname }}
      - /nfs/log/{{ ansible_default_ipv4.address }}
