#!/usr/bin/env ansible-playbook
---
- hosts: bp1
  tasks:
  - name: Ensure nfs directories
    file:
      path: "{{item}}"
      state: directory
      mode: 0775
      owner: root
      group: root
    with_items:
      - /nfs/pihole
      - /nfs/pihole/etc
      - /nfs/pihole/dnsmasq.d
      - /nfs/network_devices
      - /nfs/ircd-hybrid
      - /nfs/hubot
      - /nfs/redis
      - /nfs/src
      - /nfs/src/{{ ansible_hostname}}
      - /nfs/log
      - /nfs/log/{{ ansible_hostname}}
      - /nfs
  roles:
    - geerlingguy.nfs

- hosts: nfs-clients
  roles:
  - role: openmicroscopy.nfs-mount
    nfs_share_mounts:
      - path: /nfs
        location: bp1.pouliot.net:/nfs
        passno: 0
  tasks:
  - name: Ensure directories
    file:
      path: "{{item}}"
      state: directory
      mode: 0775
      owner: root
      group: root
    with_items:
      - /nfs/src/{{ ansible_hostname}}
      - /nfs/log/{{ ansible_hostname}}
