#!/usr/bin/env ansible-playbook
---
- hosts: bp1
  tasks:
  - name: Ensure nfs directories
    file:
      path: "{{item}}"
      state: directory
      mode: 0775
      owner: root
      group: root
    with_items:
      - /nfs
      - /nfs/redis
      - /nfs/hubot
  roles:
    - geerlingguy.nfs

- hosts: nfs-clients
  roles:
  - role: openmicroscopy.nfs-mount
    nfs_share_mounts:
      - path: /nfs
        location: bp1.pouliot.net:/nfs
        passno: 0
