#!/usr/bin/env ansible-playbook
---
- name: Update Apt Packages
  hosts: model-b
  any_errors_fatal: true
  tasks:
  - name: Update package cache
    apt:
        update_cache: yes
        upgrade: yes
  - name: Upgrade all packages to the latest version
    apt:
        name: "*"
        state: latest
  - name: Clean UnWanted Packages
    apt:
        autoremove: yes
        purge: yes
  - name: Installing Required Packages
    apt: 'name={{item}} state=present update_cache=yes'
    with_items:
      - "wget"
      - "curl"
      - "rsync"
      - "screen"
      - "tree"
      - "git"
