#!/usr/bin/env ansible-playbook
---
- name: Pin Docker-CE to version 18.06.1-ce due to upstream problems
  gather_facts: False
  hosts: model-b
  tasks:
  - script: ../files/pin_docker-ce.sh  creates=/root/consoled.txt
