#! /usr/bin/env ansible-playbook
---
- name: Add folders for services
  hosts: bpc
  sudo: True
  vars:
  tasks:
    - name: Create syncthing Directories
      file: 'path="{{ item }}" state=directory'
      with_items:
        - "/opt/syncthing/"
        - "/opt/syncthing/config"
        - "/opt/syncthing/data"
    - name: Create Deluge Directories
      file: 'path="{{ item }}" state=directory'
      with_items:
        - "/opt/syncthing/deluge/config"
        - "/opt/syncthing/deluge/data"
    - name: Create nzbget Directories
      file: 'path="{{ item }}" state=directory'
      with_items:
        - "/opt/syncthing/nzbget/config"
        - "/opt/syncthing/nzbget/data"
    - name: Create Jackett Directories
      file: 'path="{{ item }}" state=directory'
      with_items:
        - "/opt/syncthing/jackett/config"
        - "/opt/syncthing/jackett/data"
    - name: Create Cardigann Directories
      file: 'path="{{ item }}" state=directory'
      with_items:
        - "/opt/syncthing/cardigann/config"
        - "/opt/syncthing/cardigann/data"
