#!/usr/bin/env ansible-playbook
---
- name: update apt packages
  hosts: model-b
  any_errors_fatal: true
  tasks:
  - apt:
        update_cache: yes
        upgrade: yes
  - name: Upgrade all packages to the latest version
    apt:
        name: "*"
        state: latest
  - name: Clean UnWanted Packages
    apt:
        autoremove: yes
        purge: yes
