---
# tasks file for roles/nfs-mount

- name: Install NFS mount utility
  become: yes
  yum:
    name: nfs-utils
    state: present
  when: ansible_os_family == "RedHat"

- name: Install NFS mount utility
  become: yes
  apt:
    pkg: nfs-common
    state: latest
  when: ansible_os_family == "Debian"

# Do not create mountpoint using file, the mount module will create it
# automatically. This avoids problems where the module tries to change
# permissions on an existing directory

- name: Mount NFS share
  become: yes
  mount:
    fstype: nfs4
    name: "{{ item.path }}"
    opts: "{{ item.opts | default(nfs_mount_opts) }}"
    src: "{{ item.location }}"
    dump: "{{ item.dump | default(omit) }}"
    passno: "{{ item.passno | default(omit) }}"
    state: mounted
  with_items: "{{ nfs_share_mounts }}"
